services:
  - type: web
    name: infosys-kg-dashboard
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: NEO4J_URI
        sync: false
      - key: NEO4J_USER
        sync: false
      - key: NEO4J_PASSWORD
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: NGROK_TOKEN
        sync: false
