name: Keep Streamlit Alive

on:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
  workflow_dispatch:

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -L --max-time 60 \
          https://aiknowledgegraphbuilderforenterpriseinteligence.streamlit.app/
          echo "Pinged successfully"